version: "3"
services:
  go-dev:
    container_name: go-dev
    image: sdator/go
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ~/.ssh:/home/vscode/.ssh:cached
      - ..:/workspace:cached
    tty: true
    user: vscode
    working_dir: /workspace